import type { CodeIndex } from './code.js';
import { symbolRef } from './code.js';
import type { ProcessIndex } from './process.js';
import type { CodeCluster, CheckResult } from './inspect.js';
import type { RouteMap } from './api.js';
import type { TaintResult } from './taint.js';
import type { MemoryNode } from '../types.js';

/**
 * Documentation generated from what is already known, and nothing else.
 *
 * Every page here is derived: the declarations in the graph, the flows built
 * from it, the routes read from the source, the invariants, and the decisions
 * somebody recorded. No sentence is invented. A model may be asked to write
 * prose on top -- but only one that was named explicitly, and the page says
 * which pages a model touched and which it did not.
 *
 * That constraint is the point. Generated documentation that reads as though a
 * person wrote it, and quietly contains a model's guess about why something
 * exists, is worse than no documentation: it is a plausible answer with no
 * source, and the next reader cannot tell it from the recorded one.
 */

export interface WikiPage {
  /** Relative to the wiki directory, always with forward slashes. */
  path: string;
  title: string;
  body: string;
  /** Where the content came from, for the provenance line. */
  derivedFrom: string[];
}

export interface WikiInput {
  project: string;
  commit: string | null;
  generatedAt: string;
  index: CodeIndex;
  processes: ProcessIndex;
  clusters: CodeCluster[];
  routes: RouteMap;
  checks: CheckResult;
  taint: TaintResult;
  memories: MemoryNode[];
}

function provenance(page: WikiPage, input: WikiInput): string {
  return [
    '',
    '---',
    '',
    `*Generated from ${page.derivedFrom.join(', ')} at commit \`${input.commit ?? 'unknown'}\`, ${input.generatedAt}.`,
    'Every line above is derived from the code graph, the recorded memory, or the source text.',
    'No prose here was written by a language model. Do not edit this file: it is rebuilt from the repository.*',
    '',
  ].join('\n');
}

const slug = (text: string): string =>
  text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'page';

/** The pages, in the order a reader meets them. */
export function wikiPages(input: WikiInput): WikiPage[] {
  const pages: WikiPage[] = [];
  const files = new Set<string>();
  for (const symbol of input.index.symbols.values()) files.add(symbol.filePath);

  // ---- index
  const overview: string[] = [
    `# ${input.project}`,
    '',
    'What this repository contains, as the code graph sees it.',
    '',
    '| | |',
    '|---|---|',
    `| files with declarations | ${files.size} |`,
    `| declarations | ${input.index.symbols.size} |`,
    `| execution flows | ${input.processes.processes.length} |`,
    `| HTTP routes | ${input.routes.summary.routes} |`,
    `| recorded memories | ${input.memories.length} |`,
    '',
    '## Where to start',
    '',
  ];
  const entryPoints = input.processes.processes.slice(0, 10);
  if (entryPoints.length === 0) {
    overview.push('No execution flow was built: nothing here is both uncalled and calls something else.');
  } else {
    overview.push('The flows with the most steps. Each is an entry point and what it reaches.', '');
    for (const process of entryPoints) {
      overview.push(`- [\`${process.name}\`](flows.md#${slug(process.name)}) — ${process.steps.length} step(s), ${process.entry.filePath}`);
    }
  }
  overview.push('', '## Pages', '',
    '- [Execution flows](flows.md)',
    '- [HTTP surface](routes.md)',
    '- [Areas of the code](areas.md)',
    '- [Recorded decisions](decisions.md)',
    '- [What the checks say](checks.md)');
  pages.push({
    path: 'index.md',
    title: input.project,
    body: overview.join('\n'),
    derivedFrom: ['the code graph', 'the execution flows', 'the route patterns', 'the memory store'],
  });

  // ---- flows
  const flows: string[] = ['# Execution flows', '',
    'An entry point is a declaration nothing in this repository calls, which calls other declarations.',
    'That rule finds route handlers, commands and `main` — and dead code, which cannot be told apart from a function only a framework calls.',
    ''];
  for (const process of input.processes.processes.slice(0, 40)) {
    flows.push(`## ${process.name}`, '',
      `\`${process.entry.filePath}:${process.entry.startLine}\` — ${process.steps.length} step(s), depth ${process.depth}${process.truncated ? ', truncated at its limit' : ''}`,
      '');
    let depth = 0;
    for (const step of process.steps.slice(0, 25)) {
      if (step.depth !== depth) {
        depth = step.depth;
        flows.push(`**${depth} call(s) in:**`, '');
      }
      flows.push(`- \`${step.qualified}\` — ${step.filePath}:${step.startLine}`);
    }
    if (process.steps.length > 25) flows.push(`- …and ${process.steps.length - 25} more`);
    flows.push('');
  }
  pages.push({
    path: 'flows.md',
    title: 'Execution flows',
    body: flows.join('\n'),
    derivedFrom: ['the execution flows built from the call graph'],
  });

  // ---- routes
  const routes: string[] = ['# HTTP surface', ''];
  if (input.routes.routes.length === 0) {
    routes.push('No route was found.', '',
      `Patterns exist for: ${input.routes.summary.frameworksLookedFor.join(', ')}. A framework outside that list produces nothing here, which is not the same as this repository having no endpoints.`);
  } else {
    routes.push('| method | path | handler | where |', '|---|---|---|---|');
    for (const route of input.routes.routes) {
      routes.push(`| ${route.method} | \`${route.path ?? 'built at runtime'}\` | ${route.handler ? `\`${route.handler.qualified}\`` : '—'} | ${route.file}:${route.line} |`);
    }
    routes.push('', `Frameworks recognised: ${input.routes.summary.frameworks.join(', ')}.`);
  }
  routes.push('', ...input.routes.limits.map((limit) => `> ${limit}`));
  pages.push({
    path: 'routes.md',
    title: 'HTTP surface',
    body: routes.join('\n'),
    derivedFrom: ['route patterns read from the source text'],
  });

  // ---- areas
  const areas: string[] = ['# Areas of the code', '',
    'Communities in the call graph: the parts that talk to each other more than to the rest, named after the directory most of each lives in.',
    ''];
  for (const cluster of input.clusters.slice(0, 20)) {
    areas.push(`## ${cluster.name}`, '',
      `${cluster.size} declaration(s) across ${cluster.files.length} file(s).`, '',
      '**Most connected:**', '');
    for (const member of cluster.members) {
      areas.push(`- \`${member.qualified}\` — ${member.filePath}:${member.startLine} (${member.degree} edges)`);
    }
    areas.push('', '**Files:**', '', ...cluster.files.slice(0, 12).map((file) => `- \`${file}\``));
    if (cluster.files.length > 12) areas.push(`- …and ${cluster.files.length - 12} more`);
    areas.push('');
  }
  pages.push({
    path: 'areas.md',
    title: 'Areas of the code',
    body: areas.join('\n'),
    derivedFrom: ['communities in the call graph'],
  });

  // ---- decisions
  const recorded = input.memories
    .filter((memory) => memory.layer !== 'artifact' && !memory.supersededAt)
    .sort((a, b) => b.importance - a.importance || b.createdAt - a.createdAt);
  const decisions: string[] = ['# Recorded decisions', '',
    'What people recorded about this project: decisions, incidents and constraints, in their own words.',
    'This page is a copy, not a summary. Nothing here was rewritten.',
    ''];
  if (recorded.length === 0) {
    decisions.push('Nothing has been recorded yet. `dai-memory write` adds the first.');
  }
  for (const memory of recorded.slice(0, 100)) {
    decisions.push(`## ${memory.title}`, '',
      `*${memory.layer}, importance ${memory.importance}${memory.sourceRef ? `, from \`${memory.sourceRef}\`` : ''}*`, '',
      memory.body.trim(), '');
  }
  pages.push({
    path: 'decisions.md',
    title: 'Recorded decisions',
    body: decisions.join('\n'),
    derivedFrom: ['the memory store, copied verbatim'],
  });

  // ---- checks
  const checks: string[] = ['# What the checks say', '', '## Invariants', ''];
  if (input.checks.findings.length === 0) {
    checks.push('Nothing to report.');
  }
  for (const finding of input.checks.findings) {
    checks.push(`### ${finding.rule} (${finding.severity})`, '', finding.message, '',
      ...finding.where.map((where) => `- \`${where}\``), '');
  }
  checks.push('**What each rule examined:**', '',
    ...Object.entries(input.checks.summary.examined).map(([rule, count]) => `- ${rule}: ${count}`),
    '', '## Untrusted input', '');
  if (input.taint.findings.length === 0) {
    checks.push('No path from untrusted input to a dangerous call was found.');
  } else {
    checks.push(`${input.taint.summary.findings} place(s) where untrusted input could reach something dangerous, ${input.taint.summary.mitigated} of them with a sanitizer on the way.`, '');
    for (const finding of input.taint.findings.slice(0, 20)) {
      checks.push(`- \`${finding.source.symbol.qualified}\` (${finding.source.hit.kind}) → \`${finding.sink.symbol.qualified}\` (${finding.sink.hit.kind}) — ${Math.round(finding.confidence * 100)}%`);
    }
  }
  checks.push('', ...input.taint.limits.map((limit) => `> ${limit}`));
  pages.push({
    path: 'checks.md',
    title: 'What the checks say',
    body: checks.join('\n'),
    derivedFrom: ['the invariant checks', 'the taint analysis'],
  });

  return pages.map((page) => ({ ...page, body: `${page.body}\n${provenance(page, input)}` }));
}

export interface WikiDrift {
  path: string;
  state: 'missing' | 'changed' | 'current' | 'extra';
}

/**
 * Which pages on disk no longer match what the repository would generate.
 *
 * The comparison ignores the provenance line, which holds a timestamp and
 * would make every page look changed a second after it was written.
 */
export function wikiDrift(pages: WikiPage[], existing: Map<string, string>): WikiDrift[] {
  const withoutProvenance = (text: string): string => text.split('\n---\n')[0]!.trimEnd();
  const drift: WikiDrift[] = [];
  const generated = new Set(pages.map((page) => page.path));

  for (const page of pages) {
    const current = existing.get(page.path);
    if (current === undefined) drift.push({ path: page.path, state: 'missing' });
    else if (withoutProvenance(current) !== withoutProvenance(page.body)) drift.push({ path: page.path, state: 'changed' });
    else drift.push({ path: page.path, state: 'current' });
  }
  for (const path of existing.keys()) {
    if (!generated.has(path)) drift.push({ path, state: 'extra' });
  }
  return drift.sort((a, b) => a.path.localeCompare(b.path));
}
